FROM bitnami/spark:3.4.1

USER root

# Install Python dependencies
RUN pip install --no-cache-dir \
    pyspark \
    kafka-python \
    pandas \
    pyarrow \
    sqlalchemy \
    psycopg2-binary

WORKDIR /app

USER 1001
